import React from 'react';
import Link from 'next/link';
import {
    RiLinkedinBoxFill,
    RiGithubFill,
    RiProfileFill
} from 'react-icons/ri';

const Header = () => {
    return (
        <div
            className="
                absolute
                z-30
                w-full
                flex
                items-center
                px-16
                xl:px-0
                xl:h-[90px]
            "
        >
            <div
                className="
                    container mx-auto
                "
            >
                <div
                    className="
                        flex
                        flex-col
                        lg:flex-row
                        justify-between
                        items-center
                        gap-y-6
                        py-6
                    "
                >
                    <Link href="/">
                        <span className="font-extrabold text-2xl">Danang</span>
                        {' '}
                        <span className="font-light text-2xl">Purbojati</span>
                        <span className="text-accent text-4xl">.</span>
                    </Link>
                    <div
                        className="
                            flex
                            items-center
                            gap-x-5
                            text-lg
                        "
                    >
                        <a 
                            target="_blank"
                            href="https://www.linkedin.com/in/danang-wahyu-purbojati-b03902b4/"
                            className="
                                hover:text-accent
                                transition-all
                                duration-300
                                relative
                                group
                            "
                        >
                            <RiLinkedinBoxFill className="text-2xl" />
                            <div
                                className="
                                    absolute
                                    pt-[10px]
                                    top-[100%]
                                    right-[50%]
                                    translate-x-1/2
                                    hidden
                                    xl:group-hover:flex
                                "
                            >
                                <div
                                    className="
                                        bg-white
                                        relative
                                        flex
                                        text-primary
                                        items-center
                                        p-[6px]
                                        rounded-[3px]
                                        xl:group-hover:text-accent
                                    "
                                >
                                    <div
                                        className="
                                            text-[10px]
                                            leading-none
                                            font-semibold
                                            capitalize
                                        "
                                    >
                                        Linkedin
                                    </div>
                                    <div 
                                        className="
                                            border-solid
                                            border-l-white
                                            border-l-8
                                            border-y-transparent
                                            border-y-[6px]
                                            border-r-0
                                            absolute
                                            -top-[10px]
                                            right-[50%]
                                            translate-x-1/2
                                            rotate-[270deg]
                                        "
                                    />
                                </div>
                            </div>
                        </a>
                        <a 
                            target="_blank"
                            href="https://github.com/danangpurbojati"
                            className="
                                hover:text-accent
                                transition-all
                                duration-300
                                relative
                                group
                            "
                        >
                            <RiGithubFill className="text-2xl" />
                            <div
                                className="
                                    absolute
                                    pt-[10px]
                                    top-[100%]
                                    right-[50%]
                                    translate-x-1/2
                                    hidden
                                    xl:group-hover:flex
                                "
                            >
                                <div
                                    className="
                                        bg-white
                                        relative
                                        flex
                                        text-primary
                                        items-center
                                        p-[6px]
                                        rounded-[3px]
                                        xl:group-hover:text-accent
                                    "
                                >
                                    <div
                                        className="
                                            text-[10px]
                                            leading-none
                                            font-semibold
                                            capitalize
                                        "
                                    >
                                        Github
                                    </div>
                                    <div 
                                        className="
                                            border-solid
                                            border-l-white
                                            border-l-8
                                            border-y-transparent
                                            border-y-[6px]
                                            border-r-0
                                            absolute
                                            -top-[10px]
                                            right-[50%]
                                            translate-x-1/2
                                            rotate-[270deg]
                                        "
                                    />
                                </div>
                            </div>
                        </a>
                        <a 
                            target="_blank"
                            href="/"
                            className="
                                hover:text-accent
                                transition-all
                                duration-300
                                relative
                                group
                            "
                        >
                            <RiProfileFill className="text-2xl" />
                            <div
                                className="
                                    absolute
                                    pt-[10px]
                                    top-[100%]
                                    right-[50%]
                                    translate-x-1/2
                                    hidden
                                    xl:group-hover:flex
                                "
                            >
                                <div
                                    className="
                                        bg-white
                                        relative
                                        flex
                                        text-primary
                                        items-center
                                        p-[6px]
                                        rounded-[3px]
                                        xl:group-hover:text-accent
                                    "
                                >
                                    <div
                                        className="
                                            text-[10px]
                                            leading-none
                                            font-semibold
                                            capitalize
                                            text-center
                                        "
                                    >
                                        Download CV
                                    </div>
                                    <div 
                                        className="
                                            border-solid
                                            border-l-white
                                            border-l-8
                                            border-y-transparent
                                            border-y-[6px]
                                            border-r-0
                                            absolute
                                            -top-[10px]
                                            right-[50%]
                                            translate-x-1/2
                                            rotate-[270deg]
                                        "
                                    />
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Header;